hellomake : imageReading.cpp rotation.cpp flip.cpp negative.cpp sepia.cpp brightness.cpp contrast.cpp gammaCorrection.cpp dilation.cpp 				erosion.cpp blur.cpp sobel.cpp grayscale.cpp posterization.cpp sharpen.cpp

	g++ -Wall imageReading.cpp rotation.cpp flip.cpp negative.cpp sepia.cpp brightness.cpp contrast.cpp gammaCorrection.cpp dilation.cpp erosion.cpp blur.cpp sobel.cpp grayscale.cpp posterization.cpp sharpen.cpp -o runnable
